#!/usr/bin/env python3

import socket
import sys
import os

SOCKET_NAME = "/tmp/canito.socket"

def main():
    user_search = ' '.join(sys.argv[1:])
    youtube_search = '{} "Auto-generated by YouTube"'.format(user_search)
    mpv_file = 'ytdl://ytsearch1:{}'.format(youtube_search)

    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as s:
        player_connected = connect_player(s)
        if player_connected:
            print("Adding {} to the playlist.".format(user_search))
            append_to_playlist(s, mpv_file)
        else:
            spawn_new_player(mpv_file)

def append_to_playlist(s, mpv_file):
    mpv_file = mpv_file.replace('"', '\\"')
    mpv_command = 'loadfile "{}" append\n'.format(mpv_file)
    s.sendall(mpv_command.encode())

def spawn_new_player(mpv_file):
    mpv_invocation = [
        "mpv",
        mpv_file,
        "--no-video",
        "--term-playing-msg='${media-title}'",
        "--input-ipc-server={}".format(SOCKET_NAME)
    ]
    # start mpv and replace this current process
    os.execvp(mpv_invocation[0], mpv_invocation)

def connect_player(s):
    try:
        s.connect(SOCKET_NAME)
        return True
    except FileNotFoundError:
        return False
    except ConnectionRefusedError:
        return False

if __name__ == "__main__":
    main()