#!/usr/bin/env python3

import sys, os

def main():
    user_search = ' '.join(sys.argv[1:])
    youtube_search = '{} "Auto-generated by YouTube"'.format(user_search)
    
    mpv_invocation = [
        "mpv",
        'ytdl://ytsearch1:{}'.format(youtube_search),
        "--no-video",
        "--term-playing-msg='${media-title}'",
    ]
    
    # start mpv and replace this current process
    os.execvp(mpv_invocation[0], mpv_invocation)

if __name__ == "__main__":
    main()