#!/usr/bin/env python3

import socket
import sys
import os

SOCKET_NAME = "/tmp/canito.socket"

def main():
    user_search = ' '.join(sys.argv[1:])
    youtube_search = '{} "Auto-generated by YouTube"'.format(user_search)

    mpv_invocation = [
        "mpv",
        'ytdl://ytsearch1:{}'.format(youtube_search),
        "--no-video",
        "--term-playing-msg='${media-title}'",
        "--input-ipc-server={}".format(SOCKET_NAME)
    ]

    if is_player_running():
        sys.exit('mpv is already running')

    # start mpv and replace this current process
    os.execvp(mpv_invocation[0], mpv_invocation)

def is_player_running():
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as s:
        try:
            s.connect(SOCKET_NAME)
            return True
        except FileNotFoundError:
            return False
        except ConnectionRefusedError:
            return False

if __name__ == "__main__":
    main()