# Copyright 2018 goppacode (Michael Rosenthal)
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

from __future__ import unicode_literals
import youtube_dl

class Searcher:

    @staticmethod
    def search(query, autogenerated=True):
        ydl_url = Searcher.construct_ydl_url(query, autogenerated)
        with youtube_dl.YoutubeDL() as ydl:
            info_result = ydl.extract_info(ydl_url, download=False)
            entry = next(iter(info_result["entries"]), None)
            url = entry["webpage_url"]
            return url

    @staticmethod
    def construct_ydl_url(query, autogenerated):
        if(autogenerated):
            query = '{} "Auto-generated by YouTube"'.format(query)
        return 'ytsearch1:{}'.format(query)